<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TracNghiemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('trac_nghiems')->delete();
        DB::table('trac_nghiems')->truncate();
        DB::table('trac_nghiems')->insert([
            //1
            [
                'khoa_hoc_id' => 1,
                'cau_hoi' => 'Node.js sử dụng engine nào để chạy JavaScript?',
                'dap_an_1' => 'SpiderMonkey',
                'dap_an_2' => 'V8',
                'dap_an_3' => 'Chakra',
                'dap_an_4' => 'JavaScriptCore',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 1,
                'cau_hoi' => 'Node.js được phát triển bởi ai?',
                'dap_an_1' => 'Ryan Dahl',
                'dap_an_2' => 'Brendan Eich',
                'dap_an_3' => 'Linus Torvalds',
                'dap_an_4' => 'Guido van Rossum',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 1,
                'cau_hoi' => 'Node.js có thể chạy trên hệ điều hành nào?',
                'dap_an_1' => 'Windows',
                'dap_an_2' => 'Linux',
                'dap_an_3' => 'macOS',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 1,
                'cau_hoi' => 'Node.js sử dụng mô hình lập trình nào?',
                'dap_an_1' => 'Lập trình đồng bộ',
                'dap_an_2' => 'Lập trình bất đồng bộ',
                'dap_an_3' => 'Lập trình hướng đối tượng',
                'dap_an_4' => 'Lập trình hàm',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 1,
                'cau_hoi' => 'Node.js là gì?',
                'dap_an_1' => 'Một ngôn ngữ lập trình',
                'dap_an_2' => 'Một framework',
                'dap_an_3' => 'Một môi trường chạy JavaScript',
                'dap_an_4' => 'Một thư viện',
                'dap_an_dung' => 3,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 1,
                'cau_hoi' => 'Lệnh nào dùng để khởi tạo một project Node.js?',
                'dap_an_1' => 'node init',
                'dap_an_2' => 'npm init',
                'dap_an_3' => 'node start',
                'dap_an_4' => 'npm install',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            //2
            [
                'khoa_hoc_id' => 2,
                'cau_hoi' => 'ES6 là phiên bản nào của JavaScript?',
                'dap_an_1' => 'Phiên bản đầu tiên',
                'dap_an_2' => 'Phiên bản thứ hai',
                'dap_an_3' => 'Phiên bản thứ ba',
                'dap_an_4' => 'Phiên bản thứ sáu',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 2,
                'cau_hoi' => 'Arrow function trong ES6 có cú pháp như thế nào?',
                'dap_an_1' => 'function() {}',
                'dap_an_2' => '() => {}',
                'dap_an_3' => '=> {}',
                'dap_an_4' => 'function => {}',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 2,
                'cau_hoi' => 'Spread operator trong ES6 được sử dụng để làm gì?',
                'dap_an_1' => 'Gộp mảng',
                'dap_an_2' => 'Tách mảng',
                'dap_an_3' => 'Sao chép mảng',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 2,
                'cau_hoi' => 'Template literals trong ES6 được sử dụng để làm gì?',
                'dap_an_1' => 'Khai báo biến',
                'dap_an_2' => 'Tạo chuỗi đa dòng',
                'dap_an_3' => 'Tạo hàm',
                'dap_an_4' => 'Tạo đối tượng',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 2,
                'cau_hoi' => 'Destructuring trong ES6 là gì?',
                'dap_an_1' => 'Tách biến từ mảng hoặc đối tượng',
                'dap_an_2' => 'Ghép mảng',
                'dap_an_3' => 'Tạo hàm',
                'dap_an_4' => 'Tạo đối tượng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 2,
                'cau_hoi' => 'Từ khóa nào dùng để khai báo biến trong ES6?',
                'dap_an_1' => 'var',
                'dap_an_2' => 'let',
                'dap_an_3' => 'const',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            //3
            [
                'khoa_hoc_id' => 3,
                'cau_hoi' => 'React là gì?',
                'dap_an_1' => 'Một thư viện JavaScript',
                'dap_an_2' => 'Một framework JavaScript',
                'dap_an_3' => 'Một ngôn ngữ lập trình',
                'dap_an_4' => 'Một công cụ xây dựng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 3,
                'cau_hoi' => 'React được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Facebook',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Apple',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 3,
                'cau_hoi' => 'JSX là gì trong React?',
                'dap_an_1' => 'Một cú pháp mở rộng cho JavaScript',
                'dap_an_2' => 'Một thư viện CSS',
                'dap_an_3' => 'Một framework',
                'dap_an_4' => 'Một ngôn ngữ lập trình',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 3,
                'cau_hoi' => 'Virtual DOM là gì trong React?',
                'dap_an_1' => 'Một phiên bản ảo của DOM',
                'dap_an_2' => 'Một thư viện CSS',
                'dap_an_3' => 'Một framework',
                'dap_an_4' => 'Một ngôn ngữ lập trình',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 3,
                'cau_hoi' => 'Component trong React là gì?',
                'dap_an_1' => 'Một phần của giao diện người dùng',
                'dap_an_2' => 'Một hàm',
                'dap_an_3' => 'Một biến',
                'dap_an_4' => 'Một đối tượng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 3,
                'cau_hoi' => 'Hook nào dùng để quản lý state trong React?',
                'dap_an_1' => 'useState',
                'dap_an_2' => 'useEffect',
                'dap_an_3' => 'useContext',
                'dap_an_4' => 'useReducer',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //4
            [
                'khoa_hoc_id' => 4,
                'cau_hoi' => 'Thư viện nào phổ biến cho Data Science với Python?',
                'dap_an_1' => 'NumPy',
                'dap_an_2' => 'Laravel',
                'dap_an_3' => 'Spring',
                'dap_an_4' => 'Vue.js',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 4,
                'cau_hoi' => 'Python được phát triển bởi ai?',
                'dap_an_1' => 'Guido van Rossum',
                'dap_an_2' => 'James Gosling',
                'dap_an_3' => 'Bjarne Stroustrup',
                'dap_an_4' => 'Linus Torvalds',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 4,
                'cau_hoi' => 'Python là ngôn ngữ lập trình gì?',
                'dap_an_1' => 'Hướng đối tượng',
                'dap_an_2' => 'Hướng thủ tục',
                'dap_an_3' => 'Hướng hàm',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 4,
                'cau_hoi' => 'Python có thể được sử dụng để làm gì?',
                'dap_an_1' => 'Phát triển web',
                'dap_an_2' => 'Khoa học dữ liệu',
                'dap_an_3' => 'Machine Learning',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 4,
                'cau_hoi' => 'Thư viện nào dùng để vẽ đồ thị trong Python?',
                'dap_an_1' => 'Matplotlib',
                'dap_an_2' => 'Django',
                'dap_an_3' => 'Flask',
                'dap_an_4' => 'Pandas',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 4,
                'cau_hoi' => 'Thư viện nào dùng để xử lý dữ liệu trong Python?',
                'dap_an_1' => 'NumPy',
                'dap_an_2' => 'Django',
                'dap_an_3' => 'Flask',
                'dap_an_4' => 'Matplotlib',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //5
            [
                'khoa_hoc_id' => 5,
                'cau_hoi' => 'AWS Cloud Practitioner là chứng chỉ về lĩnh vực nào?',
                'dap_an_1' => 'Cloud Computing',
                'dap_an_2' => 'Mobile App',
                'dap_an_3' => 'Game',
                'dap_an_4' => 'Database',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 5,
                'cau_hoi' => 'Dịch vụ nào không phải là dịch vụ của AWS?',
                'dap_an_1' => 'EC2',
                'dap_an_2' => 'S3',
                'dap_an_3' => 'Lambda',
                'dap_an_4' => 'Firebase',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 5,
                'cau_hoi' => 'AWS Lambda là gì?',
                'dap_an_1' => 'Dịch vụ lưu trữ',
                'dap_an_2' => 'Dịch vụ tính toán không máy chủ',
                'dap_an_3' => 'Dịch vụ mạng',
                'dap_an_4' => 'Dịch vụ cơ sở dữ liệu',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 5,
                'cau_hoi' => 'S3 trong AWS là gì?',
                'dap_an_1' => 'Dịch vụ lưu trữ đối tượng',
                'dap_an_2' => 'Dịch vụ tính toán',
                'dap_an_3' => 'Dịch vụ mạng',
                'dap_an_4' => 'Dịch vụ cơ sở dữ liệu',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 5,
                'cau_hoi' => 'Azure là dịch vụ đám mây của công ty nào?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Amazon',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'IBM',
                'dap_an_dung' => 3,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 5,
                'cau_hoi' => 'Google Cloud Platform là dịch vụ đám mây của công ty nào?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Amazon',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'IBM',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //6
            [
                'khoa_hoc_id' => 6,
                'cau_hoi' => 'Flutter dùng ngôn ngữ nào để lập trình?',
                'dap_an_1' => 'Java',
                'dap_an_2' => 'Dart',
                'dap_an_3' => 'Kotlin',
                'dap_an_4' => 'Swift',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 6,
                'cau_hoi' => 'Flutter là gì?',
                'dap_an_1' => 'Một framework phát triển ứng dụng di động',
                'dap_an_2' => 'Một ngôn ngữ lập trình',
                'dap_an_3' => 'Một thư viện JavaScript',
                'dap_an_4' => 'Một công cụ xây dựng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 6,
                'cau_hoi' => 'Widget trong Flutter là gì?',
                'dap_an_1' => 'Một phần tử giao diện người dùng',
                'dap_an_2' => 'Một hàm',
                'dap_an_3' => 'Một biến',
                'dap_an_4' => 'Một đối tượng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 6,
                'cau_hoi' => 'Hot Reload trong Flutter là gì?',
                'dap_an_1' => 'Tính năng làm mới ứng dụng mà không mất trạng thái',
                'dap_an_2' => 'Tính năng khởi động lại ứng dụng',
                'dap_an_3' => 'Tính năng xóa bộ nhớ cache',
                'dap_an_4' => 'Tính năng cập nhật phiên bản mới',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 6,
                'cau_hoi' => 'Stateful Widget trong Flutter là gì?',
                'dap_an_1' => 'Widget có thể thay đổi trạng thái',
                'dap_an_2' => 'Widget không thể thay đổi trạng thái',
                'dap_an_3' => 'Widget tĩnh',
                'dap_an_4' => 'Widget động',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 6,
                'cau_hoi' => 'Stateless Widget trong Flutter là gì?',
                'dap_an_1' => 'Widget không thể thay đổi trạng thái',
                'dap_an_2' => 'Widget có thể thay đổi trạng thái',
                'dap_an_3' => 'Widget tĩnh',
                'dap_an_4' => 'Widget động',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //7
            [
                'khoa_hoc_id' => 7,
                'cau_hoi' => 'Docker dùng để làm gì?',
                'dap_an_1' => 'Ảo hóa hệ điều hành',
                'dap_an_2' => 'Quản lý container',
                'dap_an_3' => 'Quản lý database',
                'dap_an_4' => 'Quản lý source code',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 7,
                'cau_hoi' => 'Dockerfile là gì?',
                'dap_an_1' => 'Tập tin cấu hình cho Docker',
                'dap_an_2' => 'Tập tin dữ liệu',
                'dap_an_3' => 'Tập tin mã nguồn',
                'dap_an_4' => 'Tập tin hình ảnh',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 7,
                'cau_hoi' => 'Docker Hub là gì?',
                'dap_an_1' => 'Nơi lưu trữ hình ảnh Docker',
                'dap_an_2' => 'Nơi lưu trữ mã nguồn',
                'dap_an_3' => 'Nơi lưu trữ dữ liệu',
                'dap_an_4' => 'Nơi lưu trữ container',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 7,
                'cau_hoi' => 'Docker Compose là gì?',
                'dap_an_1' => 'Công cụ quản lý nhiều container',
                'dap_an_2' => 'Công cụ quản lý một container',
                'dap_an_3' => 'Công cụ quản lý hình ảnh',
                'dap_an_4' => 'Công cụ quản lý mã nguồn',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 7,
                'cau_hoi' => 'Docker Swarm là gì?',
                'dap_an_1' => 'Công cụ quản lý cluster Docker',
                'dap_an_2' => 'Công cụ quản lý một container',
                'dap_an_3' => 'Công cụ quản lý hình ảnh',
                'dap_an_4' => 'Công cụ quản lý mã nguồn',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 7,
                'cau_hoi' => 'Docker Engine là gì?',
                'dap_an_1' => 'Phần mềm chạy Docker',
                'dap_an_2' => 'Phần mềm quản lý container',
                'dap_an_3' => 'Phần mềm quản lý hình ảnh',
                'dap_an_4' => 'Phần mềm quản lý mã nguồn',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //8
            [
                'khoa_hoc_id' => 8,
                'cau_hoi' => 'Angular là framework của ngôn ngữ nào?',
                'dap_an_1' => 'Java',
                'dap_an_2' => 'JavaScript/TypeScript',
                'dap_an_3' => 'Python',
                'dap_an_4' => 'PHP',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],

            [
                'khoa_hoc_id' => 8,
                'cau_hoi' => 'Angular được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Facebook',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Apple',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 8,
                'cau_hoi' => 'Component trong Angular là gì?',
                'dap_an_1' => 'Một phần tử giao diện người dùng',
                'dap_an_2' => 'Một hàm',
                'dap_an_3' => 'Một biến',
                'dap_an_4' => 'Một đối tượng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 8,
                'cau_hoi' => 'Service trong Angular là gì?',
                'dap_an_1' => 'Một phần tử giao diện người dùng',
                'dap_an_2' => 'Một hàm',
                'dap_an_3' => 'Một biến',
                'dap_an_4' => 'Một đối tượng',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 8,
                'cau_hoi' => '@Input trong Angular là gì?',
                'dap_an_1' => '@Input decorator để truyền dữ liệu vào component con',
                'dap_an_2' => '@Input decorator để truyền dữ liệu ra component cha',
                'dap_an_3' => '@Input decorator để tạo service',
                'dap_an_4' => '@Input decorator để tạo module',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 8,
                'cau_hoi' => '@Output trong Angular là gì?',
                'dap_an_1' => '@Output decorator để truyền dữ liệu ra component cha',
                'dap_an_2' => '@Output decorator để truyền dữ liệu vào component con',
                'dap_an_3' => '@Output decorator để tạo service',
                'dap_an_4' => '@Output decorator để tạo module',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //9
            [
                'khoa_hoc_id' => 9,
                'cau_hoi' => 'Machine Learning là gì?',
                'dap_an_1' => 'Một lĩnh vực của trí tuệ nhân tạo',
                'dap_an_2' => 'Một ngôn ngữ lập trình',
                'dap_an_3' => 'Một framework',
                'dap_an_4' => 'Một thư viện',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 9,
                'cau_hoi' => 'Thư viện nào phổ biến cho Machine Learning với Python?',
                'dap_an_1' => 'NumPy',
                'dap_an_2' => 'TensorFlow',
                'dap_an_3' => 'Django',
                'dap_an_4' => 'Flask',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 9,
                'cau_hoi' => 'Học có giám sát là gì?',
                'dap_an_1' => 'Học từ dữ liệu đã được gán nhãn',
                'dap_an_2' => 'Học từ dữ liệu chưa được gán nhãn',
                'dap_an_3' => 'Học từ dữ liệu không có cấu trúc',
                'dap_an_4' => 'Học từ dữ liệu có cấu trúc',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 9,
                'cau_hoi' => 'Học không giám sát là gì?',
                'dap_an_1' => 'Học từ dữ liệu chưa được gán nhãn',
                'dap_an_2' => 'Học từ dữ liệu đã được gán nhãn',
                'dap_an_3' => 'Học từ dữ liệu không có cấu trúc',
                'dap_an_4' => 'Học từ dữ liệu có cấu trúc',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 9,
                'cau_hoi' => 'Học tăng cường là gì?',
                'dap_an_1' => 'Học từ môi trường và phản hồi',
                'dap_an_2' => 'Học từ dữ liệu đã được gán nhãn',
                'dap_an_3' => 'Học từ dữ liệu chưa được gán nhãn',
                'dap_an_4' => 'Học từ dữ liệu không có cấu trúc',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 9,
                'cau_hoi' => 'Thuật toán nào phổ biến trong Machine Learning cơ bản?',
                'dap_an_1' => 'Linear Regression',
                'dap_an_2' => 'Bubble Sort',
                'dap_an_3' => 'DFS',
                'dap_an_4' => 'BFS',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //10
            [
                'khoa_hoc_id' => 10,
                'cau_hoi' => 'Golang là ngôn ngữ lập trình do ai phát triển?',
                'dap_an_1' => 'Microsoft',
                'dap_an_2' => 'Google',
                'dap_an_3' => 'Facebook',
                'dap_an_4' => 'Amazon',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 10,
                'cau_hoi' => 'Golang được phát hành lần đầu vào năm nào?',
                'dap_an_1' => '2005',
                'dap_an_2' => '2009',
                'dap_an_3' => '2012',
                'dap_an_4' => '2015',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 10,
                'cau_hoi' => 'Golang là ngôn ngữ lập trình gì?',
                'dap_an_1' => 'Hướng đối tượng',
                'dap_an_2' => 'Hướng thủ tục',
                'dap_an_3' => 'Hướng hàm',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 10,
                'cau_hoi' => 'Go module là gì?',
                'dap_an_1' => 'Một thư viện trong Go',
                'dap_an_2' => 'Một package trong Go',
                'dap_an_3' => 'Một project trong Go',
                'dap_an_4' => 'Một biến trong Go',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 10,
                'cau_hoi' => 'Go routine là gì?',
                'dap_an_1' => 'Một luồng thực thi nhẹ trong Go',
                'dap_an_2' => 'Một package trong Go',
                'dap_an_3' => 'Một project trong Go',
                'dap_an_4' => 'Một biến trong Go',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 10,
                'cau_hoi' => 'Go channel là gì?',
                'dap_an_1' => 'Cách giao tiếp giữa các go routine',
                'dap_an_2' => 'Một package trong Go',
                'dap_an_3' => 'Một project trong Go',
                'dap_an_4' => 'Một biến trong Go',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //11
            [
                'khoa_hoc_id' => 11,
                'cau_hoi' => 'Unity chủ yếu dùng để phát triển gì?',
                'dap_an_1' => 'Web',
                'dap_an_2' => 'Game',
                'dap_an_3' => 'Mobile App',
                'dap_an_4' => 'Database',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 11,
                'cau_hoi' => 'Unity được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Unity Technologies',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Facebook',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 11,
                'cau_hoi' => 'Unity hỗ trợ ngôn ngữ lập trình nào?',
                'dap_an_1' => 'C#',
                'dap_an_2' => 'JavaScript',
                'dap_an_3' => 'Python',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 11,
                'cau_hoi' => 'Unity Asset Store là gì?',
                'dap_an_1' => 'Nơi mua bán tài nguyên cho Unity',
                'dap_an_2' => 'Nơi lưu trữ mã nguồn',
                'dap_an_3' => 'Nơi lưu trữ dữ liệu',
                'dap_an_4' => 'Nơi lưu trữ hình ảnh',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 11,
                'cau_hoi' => 'Unity Editor là gì?',
                'dap_an_1' => 'Giao diện phát triển ứng dụng trong Unity',
                'dap_an_2' => 'Một ngôn ngữ lập trình',
                'dap_an_3' => 'Một thư viện',
                'dap_an_4' => 'Một framework',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 11,
                'cau_hoi' => 'Unity hỗ trợ phát triển ứng dụng trên nền tảng nào?',
                'dap_an_1' => 'Windows',
                'dap_an_2' => 'Android',
                'dap_an_3' => 'iOS',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            //12
            [
                'khoa_hoc_id' => 12,
                'cau_hoi' => 'MongoDB là loại cơ sở dữ liệu gì?',
                'dap_an_1' => 'NoSQL',
                'dap_an_2' => 'SQL',
                'dap_an_3' => 'Graph',
                'dap_an_4' => 'Time Series',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 12,
                'cau_hoi' => 'MongoDB được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'MongoDB Inc.',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Facebook',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 12,
                'cau_hoi' => 'MongoDB sử dụng định dạng nào để lưu trữ dữ liệu?',
                'dap_an_1' => 'JSON',
                'dap_an_2' => 'XML',
                'dap_an_3' => 'CSV',
                'dap_an_4' => 'YAML',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 12,
                'cau_hoi' => 'MongoDB hỗ trợ truy vấn dữ liệu bằng ngôn ngữ nào?',
                'dap_an_1' => 'SQL',
                'dap_an_2' => 'MQL',
                'dap_an_3' => 'NoSQL',
                'dap_an_4' => 'GraphQL',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 12,
                'cau_hoi' => 'MongoDB Atlas là gì?',
                'dap_an_1' => 'Dịch vụ cơ sở dữ liệu đám mây của MongoDB',
                'dap_an_2' => 'Một thư viện JavaScript',
                'dap_an_3' => 'Một framework',
                'dap_an_4' => 'Một ngôn ngữ lập trình',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 12,
                'cau_hoi' => 'MongoDB Compass là gì?',
                'dap_an_1' => 'Giao diện đồ họa cho MongoDB',
                'dap_an_2' => 'Một ngôn ngữ lập trình',
                'dap_an_3' => 'Một thư viện',
                'dap_an_4' => 'Một framework',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //13
            [
                'khoa_hoc_id' => 13,
                'cau_hoi' => 'CI/CD là viết tắt của?',
                'dap_an_1' => 'Continuous Integration/Continuous Deployment',
                'dap_an_2' => 'Code Integration/Code Delivery',
                'dap_an_3' => 'Cloud Integration/Cloud Deployment',
                'dap_an_4' => 'Continuous Improvement/Continuous Delivery',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 13,
                'cau_hoi' => 'Git là gì?',
                'dap_an_1' => 'Hệ thống quản lý phiên bản phân tán',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Cơ sở dữ liệu',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 13,
                'cau_hoi' => 'GitHub là gì?',
                'dap_an_1' => 'Nền tảng lưu trữ mã nguồn trên đám mây',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Cơ sở dữ liệu',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 13,
                'cau_hoi' => 'Docker là gì?',
                'dap_an_1' => 'Nền tảng ảo hóa container',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Cơ sở dữ liệu',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 13,
                'cau_hoi' => 'Jenkins là gì?',
                'dap_an_1' => 'Công cụ tự động hóa CI/CD',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Cơ sở dữ liệu',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 13,
                'cau_hoi' => 'Kubernetes là gì?',
                'dap_an_1' => 'Hệ thống quản lý container',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Cơ sở dữ liệu',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //14
            [
                'khoa_hoc_id' => 14,
                'cau_hoi' => 'Khái niệm nào liên quan đến bảo mật?',
                'dap_an_1' => 'XSS',
                'dap_an_2' => 'CSS',
                'dap_an_3' => 'HTML',
                'dap_an_4' => 'JSON',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 14,
                'cau_hoi' => 'Tấn công nào liên quan đến việc giả mạo yêu cầu?',
                'dap_an_1' => 'CSRF',
                'dap_an_2' => 'XSS',
                'dap_an_3' => 'SQL Injection',
                'dap_an_4' => 'Command Injection',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 14,
                'cau_hoi' => 'Tấn công nào liên quan đến việc chèn mã SQL độc hại?',
                'dap_an_1' => 'SQL Injection',
                'dap_an_2' => 'XSS',
                'dap_an_3' => 'CSRF',
                'dap_an_4' => 'Command Injection',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 14,
                'cau_hoi' => 'Tấn công nào liên quan đến việc thực thi lệnh hệ thống?',
                'dap_an_1' => 'Command Injection',
                'dap_an_2' => 'XSS',
                'dap_an_3' => 'CSRF',
                'dap_an_4' => 'SQL Injection',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 14,
                'cau_hoi' => 'XSS là gì?',
                'dap_an_1' => 'Cross-Site Scripting',
                'dap_an_2' => 'Cross-Site Request Forgery',
                'dap_an_3' => 'SQL Injection',
                'dap_an_4' => 'Command Injection',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 14,
                'cau_hoi' => 'CSRF là gì?',
                'dap_an_1' => 'Cross-Site Request Forgery',
                'dap_an_2' => 'Cross-Site Scripting',
                'dap_an_3' => 'SQL Injection',
                'dap_an_4' => 'Command Injection',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //15
            [
                'khoa_hoc_id' => 15,
                'cau_hoi' => 'SQL dùng để làm gì?',
                'dap_an_1' => 'Quản lý cơ sở dữ liệu quan hệ',
                'dap_an_2' => 'Thiết kế giao diện',
                'dap_an_3' => 'Lập trình nhúng',
                'dap_an_4' => 'Quản lý hệ điều hành',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 15,
                'cau_hoi' => 'SQL là viết tắt của?',
                'dap_an_1' => 'Structured Query Language',
                'dap_an_2' => 'Simple Query Language',
                'dap_an_3' => 'Standard Query Language',
                'dap_an_4' => 'System Query Language',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 15,
                'cau_hoi' => 'MySQL là gì?',
                'dap_an_1' => 'Hệ quản trị cơ sở dữ liệu mã nguồn mở',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Công cụ phát triển ứng dụng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 15,
                'cau_hoi' => 'PostgreSQL là gì?',
                'dap_an_1' => 'Hệ quản trị cơ sở dữ liệu mã nguồn mở',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Công cụ phát triển ứng dụng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 15,
                'cau_hoi' => 'MongoDB là gì?',
                'dap_an_1' => 'Hệ quản trị cơ sở dữ liệu NoSQL',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Công cụ phát triển ứng dụng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 15,
                'cau_hoi' => 'SQLite là gì?',
                'dap_an_1' => 'Hệ quản trị cơ sở dữ liệu nhúng',
                'dap_an_2' => 'Ngôn ngữ lập trình',
                'dap_an_3' => 'Framework',
                'dap_an_4' => 'Công cụ phát triển ứng dụng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //16
            [
                'khoa_hoc_id' => 16,
                'cau_hoi' => 'GraphQL là gì?',
                'dap_an_1' => 'Một ngôn ngữ truy vấn API',
                'dap_an_2' => 'Một framework CSS',
                'dap_an_3' => 'Một hệ điều hành',
                'dap_an_4' => 'Một loại database',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 16,
                'cau_hoi' => 'GraphQL được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Facebook',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Apple',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 16,
                'cau_hoi' => 'GraphQL cho phép truy vấn dữ liệu như thế nào?',
                'dap_an_1' => 'Theo cấu trúc cây',
                'dap_an_2' => 'Theo bảng',
                'dap_an_3' => 'Theo danh sách',
                'dap_an_4' => 'Theo đồ thị',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 16,
                'cau_hoi' => 'GraphQL có thể thay thế REST API không?',
                'dap_an_1' => 'Có',
                'dap_an_2' => 'Không',
                'dap_an_3' => 'Chỉ trong một số trường hợp',
                'dap_an_4' => 'Tùy thuộc vào dự án',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 16,
                'cau_hoi' => 'GraphQL được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Facebook',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Apple',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 16,
                'cau_hoi' => 'GraphQL cho phép truy vấn dữ liệu như thế nào?',
                'dap_an_1' => 'Theo cấu trúc cây',
                'dap_an_2' => 'Theo bảng',
                'dap_an_3' => 'Theo danh sách',
                'dap_an_4' => 'Theo đồ thị',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //17
            [
                'khoa_hoc_id' => 17,
                'cau_hoi' => 'Swift chủ yếu dùng để phát triển ứng dụng nào?',
                'dap_an_1' => 'Android',
                'dap_an_2' => 'iOS',
                'dap_an_3' => 'Windows',
                'dap_an_4' => 'Linux',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 17,
                'cau_hoi' => 'Swift được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Apple',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Facebook',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 17,
                'cau_hoi' => 'Swift được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Apple',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Facebook',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 17,
                'cau_hoi' => 'Swift là ngôn ngữ lập trình gì?',
                'dap_an_1' => 'Hướng đối tượng',
                'dap_an_2' => 'Hướng thủ tục',
                'dap_an_3' => 'Hướng hàm',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 17,
                'cau_hoi' => 'Swift hỗ trợ tính năng nào?',
                'dap_an_1' => 'Lập trình hàm',
                'dap_an_2' => 'Lập trình hướng đối tượng',
                'dap_an_3' => 'Lập trình hướng thủ tục',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 17,
                'cau_hoi' => 'Swift có thể chạy trên nền tảng nào?',
                'dap_an_1' => 'iOS',
                'dap_an_2' => 'macOS',
                'dap_an_3' => 'Linux',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            //18
            [
                'khoa_hoc_id' => 18,
                'cau_hoi' => 'Blockchain là gì?',
                'dap_an_1' => 'Một loại cơ sở dữ liệu phân tán',
                'dap_an_2' => 'Một framework JavaScript',
                'dap_an_3' => 'Một hệ điều hành',
                'dap_an_4' => 'Một ngôn ngữ lập trình',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 18,
                'cau_hoi' => 'Blockchain được sử dụng trong lĩnh vực nào?',
                'dap_an_1' => 'Tài chính',
                'dap_an_2' => 'Y tế',
                'dap_an_3' => 'Logistics',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 18,
                'cau_hoi' => 'Blockchain có tính năng nào?',
                'dap_an_1' => 'Bảo mật',
                'dap_an_2' => 'Minh bạch',
                'dap_an_3' => 'Phân tán',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 18,
                'cau_hoi' => 'Blockchain có thể được sử dụng để làm gì?',
                'dap_an_1' => 'Giao dịch tiền điện tử',
                'dap_an_2' => 'Quản lý chuỗi cung ứng',
                'dap_an_3' => 'Lưu trữ dữ liệu',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 18,
                'cau_hoi' => 'Blockchain được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Satoshi Nakamoto',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Facebook',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 18,
                'cau_hoi' => 'Blockchain có thể được sử dụng trong lĩnh vực nào?',
                'dap_an_1' => 'Tài chính',
                'dap_an_2' => 'Y tế',
                'dap_an_3' => 'Logistics',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            //19
            [
                'khoa_hoc_id' => 19,
                'cau_hoi' => 'Flutter UI Masterclass tập trung vào gì?',
                'dap_an_1' => 'Thiết kế giao diện người dùng',
                'dap_an_2' => 'Quản lý database',
                'dap_an_3' => 'Bảo mật hệ thống',
                'dap_an_4' => 'Lập trình nhúng',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 19,
                'cau_hoi' => 'Flutter UI Masterclass sử dụng framework nào?',
                'dap_an_1' => 'React',
                'dap_an_2' => 'Flutter',
                'dap_an_3' => 'Angular',
                'dap_an_4' => 'Vue',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 19,
                'cau_hoi' => 'Flutter UI Masterclass được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Facebook',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Apple',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 19,
                'cau_hoi' => 'Flutter UI Masterclass hỗ trợ phát triển ứng dụng trên nền tảng nào?',
                'dap_an_1' => 'Android',
                'dap_an_2' => 'iOS',
                'dap_an_3' => 'Web',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 19,
                'cau_hoi' => 'Flutter UI Masterclass sử dụng ngôn ngữ lập trình nào?',
                'dap_an_1' => 'Java',
                'dap_an_2' => 'Dart',
                'dap_an_3' => 'Python',
                'dap_an_4' => 'JavaScript',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 19,
                'cau_hoi' => 'Flutter UI Masterclass được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Facebook',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Apple',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            //20
            [
                'khoa_hoc_id' => 20,
                'cau_hoi' => 'Spring Boot là framework của ngôn ngữ nào?',
                'dap_an_1' => 'Java',
                'dap_an_2' => 'Python',
                'dap_an_3' => 'PHP',
                'dap_an_4' => 'Ruby',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 20,
                'cau_hoi' => 'Spring Boot được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Pivotal Software',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Facebook',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 20,
                'cau_hoi' => 'Spring Boot được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Pivotal Software',
                'dap_an_3' => 'Microsoft',
                'dap_an_4' => 'Facebook',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 20,
                'cau_hoi' => 'Spring Boot hỗ trợ phát triển ứng dụng nào?',
                'dap_an_1' => 'Web',
                'dap_an_2' => 'Mobile App',
                'dap_an_3' => 'Desktop App',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 20,
                'cau_hoi' => 'Spring Boot sử dụng ngôn ngữ lập trình nào?',
                'dap_an_1' => 'Java',
                'dap_an_2' => 'Python',
                'dap_an_3' => 'PHP',
                'dap_an_4' => 'Ruby',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 20,
                'cau_hoi' => 'Spring Boot hỗ trợ tính năng nào?',
                'dap_an_1' => 'Tự động cấu hình',
                'dap_an_2' => 'Quản lý database',
                'dap_an_3' => 'Bảo mật hệ thống',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            //21
            [
                'khoa_hoc_id' => 21,
                'cau_hoi' => 'TypeScript là gì?',
                'dap_an_1' => 'Một superset của JavaScript',
                'dap_an_2' => 'Một framework',
                'dap_an_3' => 'Một cơ sở dữ liệu',
                'dap_an_4' => 'Một hệ điều hành',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 21,
                'cau_hoi' => 'TypeScript được phát triển bởi ai?',
                'dap_an_1' => 'Google',
                'dap_an_2' => 'Microsoft',
                'dap_an_3' => 'Facebook',
                'dap_an_4' => 'Apple',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 21,
                'cau_hoi' => 'TypeScript hỗ trợ tính năng nào?',
                'dap_an_1' => 'Kiểu tĩnh',
                'dap_an_2' => 'Kiểu động',
                'dap_an_3' => 'Lập trình hàm',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 21,
                'cau_hoi' => 'TypeScript có thể biên dịch sang ngôn ngữ nào?',
                'dap_an_1' => 'JavaScript',
                'dap_an_2' => 'Java',
                'dap_an_3' => 'Python',
                'dap_an_4' => 'C#',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 21,
                'cau_hoi' => 'TypeScript có thể chạy trên nền tảng nào?',
                'dap_an_1' => 'Web',
                'dap_an_2' => 'Mobile App',
                'dap_an_3' => 'Desktop App',
                'dap_an_4' => 'Tất cả các đáp án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'khoa_hoc_id' => 21,
                'cau_hoi' => '',
                'dap_an_1' => 'Một superset của JavaScript',
                'dap_an_2' => 'Một framework',
                'dap_an_3' => 'Một cơ sở dữ liệu',
                'dap_an_4' => 'Một hệ điều hành',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
        ]);
    }
}
